IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'InventoryDb')
BEGIN
    CREATE DATABASE [InventoryDb] COLLATE Latin1_General_CI_AS;
END
GO

ALTER DATABASE [InventoryDb] SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
GO
